### PR TITLE
Simple approach for monitoring follow and locations

### PR DESCRIPTION
**Pull request by dmvieira**
We don't have tests, so I did a simple approach for locations and follows. Twitter input must be fast and simple.

Now I'm doing test cases but it should take some time. Please take a look this code.

Regards,

### CODE REVIEW

**Comment by dmvieira** [comment]
Hi guys, what's the problem here?

**Comment by purbon** [comment]
HI @dmvieira sorry for not coming back with a more clear message, before we could move forward you need to sign the CLA, see https://www.elastic.co/contributor-agreement for more details. Keep in mind to do it with the email used to create this PR, this will simplify the internal checks.

Thanks a lot for your time and contribution.

**Comment by dmvieira** [comment]
Thx @purbon
I'm already signed!

**Comment by purbon** [comment]
Thanks @dmvieira, I see this PR need a rebase as it might be outdated with current changes in master. Can you do that please? thanks a lot.

**Comment by purbon** [comment]
On the other side, as next steps some test to "check" for this PR features might be required. If you need help moving forward with testing, please let me know.

**Comment by dmvieira** [comment]
Plugin have no tests at all... I will take a look this new master version and call you soon

**Comment by dmvieira** [comment]
Ohhhh! I see, now it has tests. I will improve it

**Comment by purbon** [comment]
oh many, of them have not test. Might be I can try to setup something to help you. As you see, we got many plugins without much of testing, or even no test, so we try to enforce all PRs with tests :+1: just add small ones for your change, no need to add for everything :+1:

**Comment by purbon** [comment]
Thanks a lot!
   looking forward to it!

- purbon

**Comment by dmvieira** [comment]
I tried some tests validating if client.filter received parameters but I don't know how...

Using before :all with rspec works, but this version of rspec don't support it yet...

I did my best :(

New ideas?

**Comment by purbon** [comment]
i will come back here soon, sorry for the long wait been traveling :+1:

**Comment by purbon** [comment]
@dmvieira I will pull your commits in a new PR where I will add test, this will make the whole thing a bit more fast and then from there I can add also some other features. what do you think?

**Comment by dmvieira** [comment]
Perfect! I don't know how to test this loop... I'm new in Ruby. Thank you so much!

**Comment by purbon** [comment]
you're welcome.

**Comment by dmvieira** [comment]
My tests were passing inside mock filter function but expect(mock).to receive(:filter).with(my_args) was asserting false with message that filter was not called, but I know it was called because I used "puts 'something'" and it works ...

**Comment by purbon** [comment]
closed in favor of #30

**Comment by purbon** [comment]
@dmvieira this is strange, and might be related with multiple threads being involved.

**Pull request closed without merging**
